### ISSUE TITLE
install note

### ISSUE THREAD

**Issue by Pomax** [huang47/ReactDraggableMixin#1]
it would be a good idea to indicate how to install this mixin in the README. A simple note to use `npm install react-draggable-mixin` clears up an important question.

**Comment by huang47** [comment]
Thanks !
https://github.com/huang47/ReactDraggableMixin/commit/23181b35d8151d609181895fdcfc5a4ef70840f1

**Comment by Pomax** [comment]
cheers! I'd recommending using the full term for `install` to stick with what every other package on npmjs.com uses, but still: thanks!
